import type { Metadata } from "next";
import { skills } from "../data";
import { SectionHead } from "../ui";

export const metadata: Metadata = { title: "About", description: "Education, experience, interests and technical journey of Sinan Anwar Alekar." };

export default function About() { return <>
  <section className="page-hero"><div className="shell"><span className="eyebrow">About me</span><h1>A student developer learning by building real products.</h1><p>Computer Engineering student with hands-on experience building full-stack web and Android applications using Python, React, FastAPI and Firebase.</p></div></section>
  <section className="section"><div className="shell prose-grid"><div><h2>My approach</h2><p>I’m passionate about Artificial Intelligence, Defensive Cybersecurity and Cloud Technologies, with practical experience developing secure authentication systems, RESTful APIs and production-oriented software.</p><p>I independently developed cross-platform applications including Sentinental IX, an AI-powered cybersecurity operations platform, and IX:X, an Android and Web learning platform. I continuously expand my technical expertise through real-world projects, modern development practices, ethical hacking labs and defensive security research.</p><p>My current learning includes secure software architecture, web application security, network fundamentals and OSCP-oriented foundations. This describes preparation and practical study—not a certification claim.</p></div><aside className="fact-card"><dl><div><dt>Location</dt><dd>Mahad, Raigad, Maharashtra, India</dd></div><div><dt>Current status</dt><dd>B.Tech student · Open to opportunities</dd></div><div><dt>Languages</dt><dd>English · Hindi · Marathi · Urdu</dd></div><div><dt>Interests</dt><dd>AI, defensive security, cloud and cross-platform products</dd></div></dl></aside></div></section>
  <section className="section alt"><div className="shell"><SectionHead eyebrow="Journey" title="Education and experience"/><div className="skill-list"><div><b>2026–Present</b><p><strong>B.Tech in Computer Engineering</strong><br/>Status: Pursuing</p></div><div><b>2025–2026</b><p><strong>Focused gap year</strong><br/>Skill development, software projects and cybersecurity preparation, including OSCP-oriented foundational learning.</p></div><div><b>2025</b><p><strong>HSC (Science)</strong><br/>Maharashtra State Board · Completed</p></div><div><b>2023–Present</b><p><strong>Freelance Technical Support & Online Research</strong><br/>Remote support, digital research, document workflows and independent client-focused problem solving.</p></div><div><b>2023</b><p><strong>SSC</strong><br/>Maharashtra State Board · Completed</p></div></div></div></section>
  <section className="section"><div className="shell"><SectionHead eyebrow="Capabilities" title="Technical toolkit"/><div className="skill-list">{skills.map(([name,value])=><div key={name}><b>{name}</b><p>{value}</p></div>)}</div></div></section>
  </>; }
