/* eslint-disable react/no-unescaped-entities -- quotation marks are intentional in the code-style hero preview */
import Link from "next/link";
import { links, projects, skills } from "./data";
import { ProjectCard, SectionHead } from "./ui";

export default function Home() { return <>
  <section className="hero"><div className="shell hero-grid"><div><span className="availability"><i /> Open to software opportunities</span><p className="kicker">Sinan Anwar Alekar</p><h1>I build practical software at the intersection of <em>AI and cybersecurity.</em></h1><p className="lead"><strong>Computer Engineering Student | Full-Stack Developer | AI &amp; Cybersecurity Enthusiast</strong><br/>I develop secure full-stack web and Android products with production-oriented architecture, clear user experiences and honest engineering decisions.</p><div className="actions"><Link className="button primary" href="/projects">View projects</Link><Link className="button" href="/resume">View resume</Link><Link className="button" href="/contact">Contact me</Link></div><div className="social-row"><a href={links.github}>GitHub ↗</a><a href={links.linkedin}>LinkedIn ↗</a><a href={links.email}>Email ↗</a></div></div><div className="hero-console" aria-label="Developer profile summary"><div className="console-top"><span/><span/><span/><b>profile.ts</b></div><pre><code><i>const</i> developer = {'{'}{`\n  name: `}<strong>"Sinan Alekar"</strong>,{`\n  focus: [`}<strong>"Full-stack"</strong>, <strong>"AI"</strong>, <strong>"Security"</strong>],{`\n  approach: `}<strong>"Build. Test. Improve."</strong>{`\n`}{'}'}</code></pre><div className="console-stat"><span>02 flagship products</span><span>Cross-platform delivery</span></div></div></div></section>
  <section className="trust-strip"><div className="shell"><span>Working with</span><b>Next.js</b><b>FastAPI</b><b>Firebase</b><b>PostgreSQL</b><b>Android</b><b>Docker</b></div></section>
  <section className="section"><div className="shell"><SectionHead eyebrow="Featured work" title="Products built to solve real problems." copy="Two independently developed applications spanning defensive security operations and cross-platform learning."/><div className="projects-grid"><ProjectCard project={projects[0]}/><ProjectCard project={projects[1]} image="/ixx-preview.jpg"/></div><div className="center"><Link className="button" href="/projects">View all project details</Link></div></div></section>
  <section className="section alt"><div className="shell split"><SectionHead eyebrow="Technical profile" title="A practical, full-stack toolkit." copy="From interface design to APIs, cloud data and deployment, I work across the product lifecycle."/><div className="skill-list">{skills.slice(0,4).map(([name,value])=><div key={name}><b>{name}</b><p>{value}</p></div>)}</div></div></section>
  <section className="cta"><div className="shell"><span className="eyebrow">Let’s build something useful</span><h2>Looking for a developer who learns fast and ships thoughtfully?</h2><Link className="button primary" href="/contact">Start a conversation</Link></div></section>
  </>; }
